CREATE DATABASE AULA12;
USE AULA12;

CREATE TABLE DISCIPLINA
(
nome VARCHAR(60) NOT NULL,
codigo_disciplina VARCHAR(60) NOT NULL,
PRIMARY KEY (codigo_disciplina)
) ENGINE = InnoDB;
INSERT INTO DISCIPLINA VALUES("Estatistica", 'EFB101');
INSERT INTO DISCIPLINA VALUES("LP", 'ECM202');
INSERT INTO DISCIPLINA VALUES("Banco de Dados", 'ECM300');

CREATE TABLE PROFESSOR
(
matricula SMALLINT UNSIGNED NOT NULL,
nome VARCHAR(60) NOT NULL,
idade SMALLINT UNSIGNED NOT NULL,
codigo VARCHAR(60),
PRIMARY KEY (matricula)
) ENGINE = InnoDB;
ALTER TABLE PROFESSOR ADD FOREIGN KEY (codigo) REFERENCES DISCIPLINA(codigo_disciplina);
INSERT INTO professor VALUES(1, 'Vanderlei', 20, 'EFB202');
INSERT INTO professor VALUES(2, 'Daniel', 20, 'EFB300');
INSERT INTO professor VALUES(3, 'Evandro God', 20, 'EFB202');
INSERT INTO professor VALUES(10, 'Calvetti', 20, null);

SELECT * FROM DISCIPLINA, PROFESSOR
WHERE DISCIPLINA.codigo_disciplina = PROFESSOR.codigo;


