/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio3_4;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enzooliveira
 */
public class Tela extends javax.swing.JFrame {
    
    private String[][] data = {};
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela.class.getName());

    /**
     * Creates new form Tela
     */
    public Tela() {
        super("Sistema");
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botao.setText("Adicionar");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "CPF", "Renda", "Tipo de Empregado"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        String name = JOptionPane.showInputDialog("Digite o nome da pessoa física: ");
        String surname = JOptionPane.showInputDialog("Digite o sobrenome do empregado: ");
        String cpf = JOptionPane.showInputDialog("Digite o CPF do empregado: ");
        String type = JOptionPane.showInputDialog("Digite o tipo do empregado: ").toLowerCase();
        PrivateIndividual employed = new PrivateIndividual();
        
            if (type.equals("horista")) {
                double hours = Double.parseDouble(JOptionPane.showInputDialog("Digite a quantidade de horas trabalhadas: "));
                double valuePerHour = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor por hora: "));
                employed = new HourlyEmployee(name, surname, cpf, hours, valuePerHour);
            } else if (type.equals("tarefeiro")) {
                double tasks = Double.parseDouble(JOptionPane.showInputDialog("Digite a quantidade de tarefas realizadas: "));
                double valuePerTask = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor por tarefa: "));
                employed = new TaskEmployee(name, surname, cpf, tasks, valuePerTask);
            } else if (type.equals("mensalista")) {
                double salary = Double.parseDouble(JOptionPane.showInputDialog("Digite o salário: "));
                employed = new MonthlyEmployee(name, surname, cpf, salary);
            } else if (type.equals("comissionado")) {
                double sales = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor das vendas: "));
                double comission = Double.parseDouble(JOptionPane.showInputDialog("Digite a comissão: "));
                employed = new CommissionedEmployee(name, surname, cpf, sales, comission);
            } else if (type.equals("desempregado")) {
                double insurance = Double.parseDouble(JOptionPane.showInputDialog("Digite o valor do seguro desemprego: "));
                employed = new Unemployed(name, surname, cpf, insurance);

            } else {
                JOptionPane.showMessageDialog(null, "Tipo de empregado inválido!");
            }
            
            String[] employedData = employed.listData();

            data = Arrays.copyOf(data, data.length + 1);
            data[data.length - 1] = employedData;

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.addRow(employedData);
    }//GEN-LAST:event_botaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
